// The same run with NO Qualflare service: what a config generated by the
// `npm init wdio` wizard looks like. The workers must still agree on a run id,
// which they now derive from the launcher process (src/config/launcher-id.ts).
import { config as base } from './wdio.conf.mjs';

export const config = {
  ...base,
  services: [],
};
